@Library('jenkinslibrerias') _
pipeline {
    agent any

    stages {
        stage('docker build') {
            steps {
                script {
                    dockerLib.build(DockerfilePath: "01-pipeline/Dockerfile",
                                    DockerImage: "velazalejandro/pagina_futbol:1.0.0-${BUILD_ID}",
                                    DockerContext: "01-pipeline")
                }
            }
        }
        stage('docker push') {
            steps {
                script {
                    dockerLib.push(DockerImage: "velazalejandro/pagina_futbol:1.0.0-${BUILD_ID}")
                }
            }
        }
    }
}